version: '3.8'

services:
  mp3yeet:
    build: .
    container_name: fileyeet
    ports:
      - "8336:8336"
    volumes:
      # Mounting host drives to allow access to files, mount only drives you want to use
      - C:/:/mnt/c
      - E:/:/mnt/e
    restart: unless-stopped